import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import './globals.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul className='flex p-1 space-x-2'>
            <li className='border border-white rounded-md p-1 px-2'>
              <Link href="/">Home</Link>
            </li>
            <li className='border border-white rounded-md p-1 px-2'>
              <Link href="/notes">Notes</Link>
            </li>
          </ul>
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
